[project]
name = "yycdevmap"
version = "0.3.0"
requires-python = ">=3.11"
dependencies = [
    "geopandas==1.1.1",
    "numpy==2.3.3",
    "pandas==2.3.2",
    "plotly==6.3.0",
    "sodapy==2.2.0",
    "streamlit==1.49.1",
    "watchdog==6.0.0",
]
